#!/bin/bash -e

if [ $# -ne 2 ]
then
    echo "Usage: $0 block-device backup-dir" 1>&2
    exit 1
fi

DISK="$1"
DIR=$2

# sfdisk can't parse its own output if the disk name is something complex like:
#   /dev/disk/by-id/usb-Generic_STORAGE_DEVICE_000000000251-0:0
# So resolve the name to the original simple /dev name, e.g. /dev/sdb1.
DISK="$(readlink -f $DISK)"

if [ ! -e "${DISK}1" ]
then
    echo "Error: ${DISK}1 does not exist" 1>&2
    exit 1
fi

# Unfortunately the boot partition for the Odroid C2 has partition type vfat which isn't supported
# by the fsarchiver version in Xenial (but is handled in Yakkety and later versions).
# So instead of a single fsarchiver command we have to use sfdisk and dd as well.

mkdir -p $DIR

sudo sfdisk --dump "$DISK" > $DIR/partition-table.txt
sudo dd bs=1M if="${DISK}1" | xz > $DIR/boot.img.xz
sudo fsarchiver --overwrite --jobs=4 savefs $DIR/rootfs.fsa "${DISK}2"
