#!/bin/bash -e

if [ $# -ne 3 ]
then
    echo "Usage: $0 /dev/disk/by-id/<disk-name> old-name new-name" 1>&2
    exit 1
fi

DISK="$1"
OLD_NAME=$2
NEW_NAME=$3

if [ ! -e "${DISK}-part2" ]
then
    echo "Error: ${DISK}-part2 does not exist" 1>&2
    exit 1
fi

udisksctl mount --block-device "$DISK-part2"
cd /media/$USER/rootfs/etc

sudo /bin/sh -c "echo $NEW_NAME > hostname"
sudo sed -i "s/\<$OLD_NAME\>/$NEW_NAME/" hosts

cd
udisksctl unmount --block-device "$DISK-part2"
udisksctl power-off --block-device $DISK
